{{- if and .Values.apps.webapp.enabled .Values.apps.webapp.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apps.webapp.serviceAccount.name | default "webapp" }}
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  {{- with .Values.apps.webapp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.apps.webapp.serviceAccount.automount }}
{{- end }}
